### ISSUE TITLE
item14 : Comparable을 구현할지 고려하라

### ISSUE THREAD

**Issue by sienna011022** [EffectiveStudy/study-history#6]
### item14 : Comparable을 구현할지 고려하라의 Pg 89에서 질문이 생겼습니다.!

중간쯤에 뷰 메서드를 추가하면서 '우회하는 법'에 대하여 명확히는 이해가 안가고 있습니다.
그래서 구글링을 통해 이해를 더 해보려고 했으나 더 헷갈리네여.
* 뷰 메서드를 사용하면 바깥 클래스에서 우리가 원하는 compareTo 메서드를 구현할 수 있다라고 하는데 , 예시의 compareTo 메서드를 보면 뷰 메서드인 asApple이 어떻게 쓰이는지 모르겠더라고요..!
예시 코드를 구글링해서 가져와봤습니다.😂예시 코드 잘못인지..흠 함께 보며 파악하면 좋을 것 같습니다!!

예시 가져온 블로그입니당
https://hyeon9mak.github.io/Effective-Java-item14/ 

``` 
public class Apple implements Comparable<Apple> {
    private int price;
    private int weight;

    public Apple(int price, int weight) {
        this.price = price;
        this.weight = weight;
    }

    @Override
    public int compareTo(Apple apple) {
        int result = Integer.compare(price, apple.price);
        if (result == 0) {
            return Integer.compare(weight, apple.weight);
        }
        return result;
    }
}

// View 메서드(asApple)를 제공
class GreenApple implements Comparable<GreenApple> {
    private Apple apple;
    private int green;

    public GreenApple(Apple apple, int green) {
        this.apple = apple;
        this.green = green;
    }

    public Apple asApple() {
        return apple;
    }

    @Override
    public int compareTo(GreenApple greenApple) {
        int result = apple.compareTo(greenApple.apple);
        if (result == 0) {
            return Integer.compare(green, greenApple.apple);
        }
        return result;
    }
}

**Comment by SanghoLee-dev** [comment]
위회하는 법이란 item 10 에서 나온 추이성을 지키기 위함과 같은 내용인거 같습니다.
객체지향적 추상화 적인 코드라면 아래 처럼 상속을 통해 확장한다면
```java
public class GreenApple extends Apple {
    private int green;
    ...
}
```
추이성 규약을 지키기 어려워서 위 올려주신 예제 처럼 Composition 형태로 우회한다는 거 같습니다.
대신 Composition 형태로 우회하면 상속 했을때 이점을 사용할 수 없으니 뷰 메소드로 내부 인스턴스를 제공 해라
이런 의미 인거 같습니다.

---
결론은 뷰 메소드는 `compareTo` 메소드랑 상관없고 Composition 형태로 확장에 따른 필요 메소드? 인거 같습니다.
